### ISSUE TITLE
[HELP WANTED]: Using Perplexity Pro API key

### ISSUE THREAD

**Issue by sitharavs** [AIHawk-app/Auto_Jobs_Applier#474]
### Issue description

I have a Perplexity Pro subscription and I generated API keys.  When I use this key in the secrets.yaml file, the bot runs but it doesn't apply the job. It just discards the application and throws an error "Invalid API key" 
Do you guys have any idea how we could fix this issue? 

### Specific tasks

Update: I realized that this code doesn't yet support Perplexity, could you please push the updated code to this GitHub which accommodates perplexity models as well? Since they are offering a lot of discounts on buying subscription, its easier to use this tool with perplexity

**Comment by sitharavs** [comment]
Can someone please modify the code and reply to this comment if it's done. Perplexity is launching good offers to buy their subscription and API keys. I want to use these keys and run it with my resume. Please help!

**Comment by LasyShark** [comment]
There is no function supporting Perplexity yet. Stating this as I've already tried using my Perplexity API and just finished appears that despite using LLAMA the API call for Perplexity is formatted differently.

**Comment by surapuramakhil** [comment]
created this https://github.com/AIHawk-app/Auto_Jobs_Applier/issues/760
