### ISSUE TITLE
[BUG]: No matching distribution found for lib_resume_builder_AIHawk

### ISSUE THREAD

**Issue by ArtistYay** [AIHawk-app/Auto_Jobs_Applier#675]
### Describe the bug

ERROR: Ignored the following versions that require a different python version: 0.1 Requires-Python >=3.10; 0.2 Requires-Python >=3.10 ERROR: Could not find a version that satisfies the requirement lib_resume_builder_AIHawk (from versions: none) ERROR: No matching distribution found for lib_resume_builder_AIHawk

### Steps to reproduce

1. Configured files needed for the program to run.
2. Activated the virtual environment using the `python3 -m venv virtual`
3. Using a Windows 11 base machine so ran the `.\virtual\Scripts\activate` command
4. I installed the required packages using the `pip3 install—r requirements.txt` command. Initially, I had to specify the Python version I wanted to use.
5. Ran `python3 main.py` and got error for `Traceback (most recent call last):
  File "C:\Users\athin\Desktop\Auto_Jobs_Applier_AIHawk\main.py", line 11, in <module>
    from lib_resume_builder_AIHawk import Resume, FacadeManager, ResumeGenerator, StyleManager
ModuleNotFoundError: No module named 'lib_resume_builder_AIHawk'`
6. Went ahead and ran the command `python3 -m pip install lib_resume_builder_AIHawk` and got this error `ERROR: Ignored the following versions that require a different python version: 0.1 Requires-Python >=3.10; 0.2 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement lib_resume_builder_AIHawk (from versions: none)
ERROR: No matching distribution found for lib_resume_builder_AIHawk`.

![image](https://github.com/user-attachments/assets/0f720c99-b90e-4060-bdae-fc2348c7d1c2)

![image](https://github.com/user-attachments/assets/24d02f3a-97ee-4662-8d55-ae49ebf35cea)

### Expected behavior

I expected it to run.

### Actual behavior

Had an installation error for lib_resume_builder_AIHawk

### Branch

main

### Python version

3.11.9(64b)

### LLM Used

Gemini

### Model used

gemini-1.5-flash-002

### Additional context

I've been trying to troubleshoot this thing, but this is as far as I'll go. 

- The first error I was having problems with ` unsupported operand type(s) for |: 'type' and 'NoneType'`, which was resolved in issue #51 

- The second error threw me many traceback errors when using the `python main.py` command, so I used `python3 main.py` instead.

- The third error was ` No module named` for yaml, which I resolved with this command: `python3 -m pip install pyyaml`. I did the same for Selenium and the web driver. Now, it's the lib_resume_builder_AIHawk module, which makes no sense because I ran the `pip3 install—r requirements.txt` command.

**Comment by cjbbb** [comment]
try conda to create a conda environment. Just needs to pip install -r requirements.txt

**Comment by ArtistYay** [comment]
Still getting an error 
![image](https://github.com/user-attachments/assets/3e080abc-0f80-41be-a967-e3ecbc98e4b0)

**Comment by surapuramakhil** [comment]
@ArtistYay I believe experienceLevel is only in readMe. just checked main branch - we are using experience_level
