### ISSUE TITLE
[HELP WANTED]: Getting error for API Key

### ISSUE THREAD

**Issue by vrlelif** [AIHawk-app/Auto_Jobs_Applier#722]
### Issue description

I'm using my own resume with --resume arg, and the bot runs until the easy apply pop-up shows up. Then, I get this error.

Unexpected error occurred: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-11KRr***************************************u2FR. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

## Specific tasks
Run the project with or without --resume.

## Additional resources
No response

##Additional context
The API key is valid, has access to GPT-4o-mini and GPT-4o and has credit in my account.

Can anyone suggest what could cause it?

**Comment by FrancescoVassalli** [comment]
If you are sure your API key is correct then what do you have for these settings in config.yaml ? 

llm_model_type: openai
llm_model: 'gpt-4o-mini'
# llm_api_url: 'https://api.pawan.krd/cosmosrp/v1'

**Comment by vrlelif** [comment]
My bad. 
I just realized that I overlooked replacing the API key in the data_folder_example. I'm sharing this in case anyone else experiences the same issue. Thank you for your help, @FrancescoVassalli!
