### ISSUE TITLE
[BUG]: Unexpected error while parsing YAML

### ISSUE THREAD

**Issue by Dobrzinska** [AIHawk-app/Auto_Jobs_Applier#724]
### Describe the bug

clone from the master, changes exactly as described in the readme

### Steps to reproduce

clone from the master, changes exactly as described in the readme
macOS m1
Runtime error: Error running the bot
 | ERROR | main:main:219 - Runtime error: Error running the bot: Unexpected error while parsing YAML: 7 validation errors for Resume
personal_information.zip_code
String should have at most 10 characters [type=string_too_long, input_value='[Your zip code]', input_type=str]
For further information visit https://errors.pydantic.dev/2.9/v/string_too_long
personal_information.email
value is not a valid email address: An email address must have an @-sign. [type=value_error, input_value='[Your Email Address]', input_type=str]
personal_information.github
Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='[Your GitHub Profile URL]', input_type=str]
For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
personal_information.linkedin
Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='[Your LinkedIn Profile URL]', input_type=str]
For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
education_details.0.year_of_completion
Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='[Year of Completion]', input_type=str]
For further information visit https://errors.pydantic.dev/2.9/v/int_parsing
projects.0.link
Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='[Project Link]', input_type=str]
For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
projects.1.link
Input should be a valid URL, a relative URL without a base [type=url_parsing, input_value='[Project Link]', input_type=str]
For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
I have checked YAML. It's valid. Typing in an email, and changing, the postcode does not solve the problem.

### Branch

main

### Python version

3.12.5 (64 bit)

### LLM Used

Chat GPT

### Model used

GPT-4o-mini

**Comment by surapuramakhil** [comment]
@Dobrzinska what's your configured zipCode value? it should be number, can have 5 - 10 digits.

**Comment by iskandarzhilmi** [comment]
Error is the same issue from mine. My zip_code is "47120". My email is valid (with @ etc.)

**Comment by iskandarzhilmi** [comment]
Found the issue. I edited the "data_folder_example" folder not the actual "data_folder"

**Comment by FrancescoVassalli** [comment]
> Found the issue. I edited the "data_folder_example" folder not the actual "data_folder"

Can this be marked as closed?

**Comment by surapuramakhil** [comment]
yes ofcourse.
