### ISSUE TITLE
[BUG]: LinkedIn Google Sign-in Popup Not Handled Properly

### ISSUE THREAD

**Issue by haziqhilmismail** [AIHawk-app/Auto_Jobs_Applier#736]
### Describe the bug

The authenticator is not properly handling the Google sign-in popup window when trying to log in to LinkedIn. When clicking the "Sign in with Google" button, the popup window opens but the authenticator doesn't switch focus to it, preventing successful authentication.

### Steps to reproduce

1. Use main branch
2. Click "Continue with Google" on LinkedIn login page
3. Google sign-in popup appears
4. Wait ~2 seconds
5. Focus switched to the main page

### Expected behavior

Authenticator should automatically detect and handle the Google sign-in popup window, allowing the user to complete authentication before returning to the main LinkedIn window.

### Actual behavior

Authenticator remains focused on the main LinkedIn window and fails to interact with the Google sign-in popup, preventing successful authentication through Google.

### Branch

main

### Python version

3.11.0

### LLM Used

ChatGPT

### Model used

GPT-4o-mini

**Comment by rohansonawane** [comment]
Were you able to resolve the issue?

**Comment by zhawan97** [comment]
I'm having the same issue, hoping for a fix.

**Comment by rohansonawane** [comment]
> I'm having the same issue, hoping for a fix.

I resolved it by changing the LinkedIn Password to allow normal login and that works fine
